version: 2

jobs:
  build:
    machine: true
    environment:
    - DEFAULT_USER: openwrt
    - DEFAULT_SUDOSU: sudo su
    steps:
    - run:
        name: (System) Update Linux Package Management System
        command: sudo apt-get update
    - run:
        name: (System) Install Linux Base Packages and Dependencies
        command: sudo apt-get install -y sudo time git-core subversion build-essential gcc-multilib libncurses5-dev zlib1g-dev gawk flex gettext wget unzip python
    - run:
        name: (System) Create Non-Root User
        command: sudo useradd -m $DEFAULT_USER
    - checkout:
        path: ~$CIRCLE_PROJECT_REPONAME
    - run:
        name: (OpenWrt) Set Folder Permissions for Non-Root User
        command: sudo chown $DEFAULT_USER.$DEFAULT_USER ~$CIRCLE_PROJECT_REPONAME -R
    - run:
        name: (OpenWrt) Feeds Update
        command: $DEFAULT_SUDOSU $DEFAULT_USER -c "cd ~$CIRCLE_PROJECT_REPONAME && ./scripts/feeds update -a"
    - run:
        name: (OpenWrt) Feeds Install
        command: $DEFAULT_SUDOSU $DEFAULT_USER -c "cd ~$CIRCLE_PROJECT_REPONAME && ./scripts/feeds install -a"
    - run:
        name: (OpenWrt) Setup Target Configuration
        command: $DEFAULT_SUDOSU $DEFAULT_USER -c "cd ~$CIRCLE_PROJECT_REPONAME && cp vr9_default.config .config"
    - run:
        name: (OpenWrt) Build Target
        command: $DEFAULT_SUDOSU $DEFAULT_USER -c "cd ~$CIRCLE_PROJECT_REPONAME && make -j16"
        no_output_timeout: 30m         
    
    - store_artifacts:
        path: ./~Easybox-904-XDSL/bin 

